#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


function log() {
  echo [pre-commit] "$1"
}

log "Running git pre commit..."
. "$(dirname "$0")/_/husky.sh"

function hasChanges() {
  if test "$( git status --short | wc -l )" -gt 0; then
    return 0
  else
    return 1
  fi
}

if hasChanges; then
  log "Changes detected"

  log "Compiling..."
  npm run compile
  retVal=$?
  if [ $retVal -ne 0 ]; then
    log "Compilation failed, fix the errors before committing"
    exit $retVal
  fi

  # todo: our current unit test prove nothing, we need to add some real tests
  # log "Testing..."
  # npm test
  # retVal=$?
  # if [ $retVal -ne 0 ]; then
  #   log "Testing failed, fix the errors before committing"
  #   exit $retVal
  # fi

  # Update (patch) the package version numbers if changes are detected
  log "Patching package application version"
  npm version patch --no-git-tag-version
  git add package.json
  git add package-lock.json
fi
